### ISSUE TITLE
BucketBufferArray can't write after read

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/tasks#36]
In the BrokerRestart/RecoverTests there a some exceptions logs which indicates an problem on the snapshoting. 

```java
13:38:43.043 [actor-runner-broker-1] ERROR io.zeebe.logstreams - Stream processor 'workflow.default-topic.0.processor.incident' failed. Can not write snapshot.
java.lang.ArrayIndexOutOfBoundsException: -1
	at io.zeebe.map.BucketBufferArray.writeToStream(BucketBufferArray.java:489) ~[zb-map-0.1.0-20170807.075208-17.jar:0.1.0-SNAPSHOT]
	at io.zeebe.map.ZbMapSerializer.writeToStream(ZbMapSerializer.java:65) ~[zb-map-0.1.0-20170807.075208-17.jar:0.1.0-SNAPSHOT]
	at io.zeebe.logstreams.snapshot.ZbMapSnapshotSupport.writeSnapshot(ZbMapSnapshotSupport.java:50) ~[zb-logstreams-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.zeebe.logstreams.snapshot.ComposedZbMapSnapshot.writeSnapshot(ComposedZbMapSnapshot.java:71) ~[zb-logstreams-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.zeebe.logstreams.spi.SnapshotWriter.writeSnapshot(SnapshotWriter.java:60) ~[zb-logstreams-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.writeSnapshot(StreamProcessorController.java:464) [zb-logstreams-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController.ensureSnapshotWritten(StreamProcessorController.java:444) [zb-logstreams-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$ClosingSnapshottingState.doWork(StreamProcessorController.java:648) [zb-logstreams-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at io.zeebe.logstreams.processor.StreamProcessorController$ClosingSnapshottingState.doWork(StreamProcessorController.java:637) [zb-logstreams-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
```

**Comment by ThorbenLindhauer** [comment]
Review hints:

* `BucketBufferArrayIOTEst.shouldReadWriteBucketArrayFromStream` should assert all bytes of the bucket buffer array header, not just the least significant of an int value
* There are unused local variables in the test method as well as `BucketBufferArray`
* `BucketBufferArray#readInto` catches `IOException` and continues looping. This is potentially an infinite loop if the stream throws such exceptions permanently. Do not catch this exception and propagate a proper exception instead. This may require refactoring the test in https://github.com/zeebe-io/zb-util/commit/68964cd5b574c21530e6afa5eac2d6ff14be93cc, see https://github.com/zeebe-io/zb-util/issues/24#issuecomment-320684191
